jquery: //ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js
knockout: //cdnjs.cloudflare.com/ajax/libs/knockout/2.2.1/knockout-min.js
bootstrap: //netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js
markdown: /js/lib/markdown.js
textile: /js/lib/textile.js
